### PR TITLE
Fix #51

### LINKED ISSUE #51: fontconfig changes R locale
Due to [this commit](https://github.com/behdad/fontconfig/commit/2938e4d72da40f6bb0d22086c519a9852a820f40), fontconfig calls do `setlocale`.
This propagates back to R and causes https://github.com/davidgohel/flextable/issues/125 .

MCVE (start in a fresh R session):

``` r
Sys.getlocale()
#> [1] "LC_COLLATE=German_Germany.1252;LC_CTYPE=German_Germany.1252;LC_MONETARY=German_Germany.1252;LC_NUMERIC=C;LC_TIME=German_Germany.1252"
fonts <- gdtools::sys_fonts()
Sys.getlocale()
#> [1] "German_Germany.1252"
```

<sup>Created on 2019-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

A possible remedy would be saving and restoring the locale on every call at the R level, akin to `withr::with_locale()`.

### PR DESCRIPTION
**Pull request by AshesITR**
Also fixes https://github.com/davidgohel/flextable/issues/125 (confirmed locally).
I'm not sure if the tests work on non-windows systems and whether the fix will work on these systems.

Windows will error out if we try to restore **all** defined LC_xxx so if we need this, additional OS-specific logic will be required.

### CODE REVIEW

**Comment by davidgohel** [comment]
@AshesITR Hi, thanks

I had time to look at that. It think it happens because the way fontconfig is called, an environment variable `FC_LANG` should be set.

I was able to solve the issue by setting FC_LANG (fortunately, rwinbuilder is there and locale is German): 

```
> oldloc <- Sys.getlocale()
> fonts <- gdtools::sys_fonts()
> oldloc
[1] "LC_COLLATE=C;LC_CTYPE=German_Germany.1252;LC_MONETARY=C;LC_NUMERIC=German_Germany.1252;LC_TIME=C"
> Sys.getlocale()
[1] "LC_COLLATE=C;LC_CTYPE=German_Germany.1252;LC_MONETARY=C;LC_NUMERIC=German_Germany.1252;LC_TIME=C"
```

Could you try the following branch and check it is working?

https://github.com/davidgohel/gdtools/tree/FC_LANG

**Comment by davidgohel** [comment]
Many thanks

I can't reproduce with winbuilder but can with a local french Windows computer. I would have been happy to have a clear fix for that issue but I did not find a satisfying solution... `systemfonts` will probably help a lot when it will be available.

The solution you provided is welcome but I'd like to change tests before merging so that it won't fail on machine when "German_Germany.1252" is not available.

Could you replace your tests with something that do not require any specific locale? The following looks ok to me and check your solution is working as expected.

```
context("locale")

test_that("locale is not modified", {
  oldloc <- Sys.getlocale()
  fonts <- gdtools::sys_fonts()
  newloc <- Sys.getlocale()
  expect_equal(oldloc, Sys.getlocale())
})
```

**Comment by AshesITR** [comment]
Hi

I can remove the test locale, but I originally used this to ensure tests will fail when the behaviour returns, even if the current locale happens to be okay.

What do you think about trying to use German_Germany.1252 (is it available on your machine?) and falling back to the current locale if this fails?

Otherwise, feel free to change `test_locale <- old_locale` at the top.

**Comment by davidgohel** [comment]
OK, I will merge later today. I can't keep your test file as is as it is failing on non windows machine (see travis results, https://travis-ci.org/davidgohel/gdtools/builds/544808393?utm_source=github_status&utm_medium=notification). Also I am not sure it works if locale set does not exists.

**Comment by AshesITR** [comment]
Sorry I took a little longer. I just pushed an updated test to master.

**Comment by davidgohel** [comment]
thanks @AshesITR , that's ok, I used my test which is enough I think to be sure your fix is working. The new version has been pushed to cran

**Comment by AshesITR** [comment]
@davidgohel Thanks a lot, looking forward to the update

**Pull request merged**
