### PR TITLE
add function to get fontconfig to reload configuration files

### PR DESCRIPTION
**Pull request by pmur002**
Hi

For one of my packages ('dvir') I added a fontconfig_reinit() function to 'gdtools' so that I could generate font configuration files on-the-fly and force fontconfig to reload them.

Would you consider adding this to the real 'gdtools' package ?

I have tried to follow the pattern of the existing code when adding this new function - apologies if I have done it wrong.

Paul

### CODE REVIEW

**Comment by davidgohel** [comment]
@pmur002 no problem. I am not available to do it this week but I will next week!

David

**Comment by pmur002** [comment]
Cool.  Thanks!

**Comment by davidgohel** [comment]
@pmur002 it's on cran now.

**Comment by pmur002** [comment]
Thanks very much.

**Pull request merged**
